#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

namespace BumiMobile
{
    // Generates a strongly-typed accessor class from AudioLibrary content:
    // AudioKeys.UI.Button => new SoundKey("UI", "Button")
    //
    // No enums to maintain; IDs come from the ScriptableObject data.
    public static class AudioRefsGenerator
    {
        private const string GeneratedPath = "Assets/Bumi/Generated Audio Keys/AudioKeys.g.cs";

        [MenuItem("Tools/Audio/Generate Audio Keys")]
        public static void GenerateNow()
        {
            GenerateFromAllLibraries();
        }

        // Regenerate when assets change (adds/removes/renames IDs)
        class Postprocessor : AssetPostprocessor
        {
            private static HashSet<string> _audioLibraryGuids;

            private static void EnsureCacheInitialized()
            {
                if (_audioLibraryGuids != null) return;

                var guids = AssetDatabase.FindAssets("t:AudioLibrary");
                _audioLibraryGuids = new HashSet<string>(guids, StringComparer.Ordinal);
            }

            static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
            {
                EnsureCacheInitialized();

                bool libraryChanged =
                    importedAssets.Any(IsLibraryPath) ||
                    deletedAssets.Any(IsLibraryPath) ||
                    movedAssets.Any(IsLibraryPath) ||
                    movedFromAssetPaths.Any(IsLibraryPath);

                if (libraryChanged)
                {
                    // Invalidate cache so it rebuilds on next check
                    _audioLibraryGuids = null;
                    GenerateFromAllLibraries();
                }
            }

            private static bool IsLibraryPath(string path)
            {
                var ext = Path.GetExtension(path);
                if (!string.Equals(ext, ".asset", StringComparison.OrdinalIgnoreCase)) return false;

                var guid = AssetDatabase.AssetPathToGUID(path);
                return _audioLibraryGuids != null && _audioLibraryGuids.Contains(guid);
            }
        }

        private static void GenerateFromAllLibraries()
        {
            var guids = AssetDatabase.FindAssets("t:AudioLibrary");
            var entries = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var lib = AssetDatabase.LoadAssetAtPath<AudioLibrary>(path);
                if (lib == null) continue;

                foreach (var group in lib.groups.Where(g => g != null && !string.IsNullOrWhiteSpace(g.name)))
                {
                    var gName = group.name.Trim();
                    if (!entries.TryGetValue(gName, out var set))
                    {
                        set = new HashSet<string>(StringComparer.Ordinal);
                        entries[gName] = set;
                    }

                    foreach (var item in group.items.Where(i => i != null && !string.IsNullOrWhiteSpace(i.id)))
                    {
                        set.Add(item.id.Trim());
                    }
                }
            }

            WriteGenerated(entries);
        }

        private static void WriteGenerated(Dictionary<string, HashSet<string>> entries)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(GeneratedPath)!);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("namespace BumiMobile");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AudioKeys");
            sb.AppendLine("    {");

            foreach (var kvp in entries.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                var groupIdentifier = SanitizeIdentifier(kvp.Key, "Group");
                sb.AppendLine($"        public static class {groupIdentifier}");
                sb.AppendLine("        {");
                foreach (var id in kvp.Value.OrderBy(x => x, StringComparer.Ordinal))
                {
                    var idIdentifier = SanitizeIdentifier(id, "Id");
                    // Property returning a SoundKey
                    sb.AppendLine($"            public static SoundKey {idIdentifier} => new SoundKey(\"{kvp.Key}\", \"{id}\");");
                }
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var existing = File.Exists(GeneratedPath) ? File.ReadAllText(GeneratedPath) : null;
            var content = sb.ToString();
            if (!string.Equals(existing, content, StringComparison.Ordinal))
            {
                File.WriteAllText(GeneratedPath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                AssetDatabase.ImportAsset(GeneratedPath);
            }
        }

        private static string SanitizeIdentifier(string raw, string fallback)
        {
            if (string.IsNullOrWhiteSpace(raw)) return fallback;

            var sb = new StringBuilder(raw.Length);
            // First character: letter or underscore
            var c0 = raw[0];
            if (char.IsLetter(c0) || c0 == '_') sb.Append(c0);
            else sb.Append('_');

            for (int i = 1; i < raw.Length; i++)
            {
                var c = raw[i];
                if (char.IsLetterOrDigit(c) || c == '_') sb.Append(c);
                else sb.Append('_');
            }

            var result = sb.ToString();

            // Avoid reserved keyword collisions minimally by suffixing underscore for common cases
            switch (result)
            {
                case "class":
                case "namespace":
                case "public":
                case "internal":
                case "protected":
                case "private":
                case "static":
                case "void":
                case "new":
                case "return":
                    result += "_";
                    break;
            }

            return result;
        }
    }
}
#endif